version: '3'

services: 
  redis:
    image: "redis:alpine"
    ports:
      - "6379"
  # postgres:
  #   image: "postgres:alpine"
  #   environment:
  #     POSTGRES_USER: kerogiro
  #     POSTGRES_DB: rental_hosts
  #   ports: 
  #     - "1458:5432"
  web: 
    image: about-server
    depends_on:
      - 'redis'
      - 'postgres'
    ports:
      - "3001:3001"
    environment:
      - DB=postgres
      - REDIS=redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
